[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake = "EGn97R6FkiA9HGRQzrrpL2w7XWY11cmUvHbtYPC6XcCR"

[registry]
url = "https://api.apr.dev"

# change cluster from "localnet" to "devnet" if you want to test the code in solana devnet
[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
